"""KPI registry: fixed a priori per Section 4.5/4.6 of the brief."""
from . import (
    anisotropy,
    connectivity,
    contacts,
    correlation,
    defects,
    dispersion,
    fractions,
    pores,
    sizes,
    vertical,
)

MODULES = [
    fractions,
    sizes,
    dispersion,
    pores,
    anisotropy,
    correlation,
    connectivity,
    contacts,
    defects,
    vertical,
]

# name -> robustness class (R/M/W), per Section 4.5 table
ROBUSTNESS = {
    "si_frac_solid": "M", "si_frac_total": "M",
    "si_d50_aw_um": "R", "si_d90_aw_um": "R", "si_d10_aw_um": "M",
    "si_span": "M", "si_num_density_mm2": "M",
    "si_solidity_med": "R", "si_aspect_med": "R", "si_circularity_med": "R",
    "si_interior_texture": "M",
    "si_quadrat_cv": "M", "si_clark_evans_R": "M", "si_agglomerate_frac": "M",
    "pore_frac_deep": "W", "pore_frac_slope_per_level": "W", "ambiguous_frac": "W",
    "pore_chord_h_mean_um": "R", "pore_chord_v_mean_um": "R",
    "pore_chord_h_p90_um": "M", "pore_lt_d50_um": "M",
    "aniso_pore_chord_ratio": "R", "aniso_carbon_chord_ratio": "R",
    "st_coherence": "R", "st_orientation_deg": "R",
    "s2_len_pore_h_px": "R", "s2_len_pore_v_px": "R", "s2_len_si_px": "R",
    "s2_integral_range_pore_px2": "R", "si_frac_se_imagerep": "R",
    "pore_percolating_frac_v": "M", "pore_percolating_frac_h": "M",
    "pore_euler_density_mm2": "M",
    "interface_pore_solid_um_per_um2": "R",
    "si_contact_pore_frac": "R", "si_contact_carbon_frac": "R",
    "crack_density_um_per_mm2": "M", "largest_void_ecd_um": "M",
    "hiz_inclusion_count_mm2": "M",
    "vertical_pore_slope": "W", "vertical_si_slope": "W",
}

# Section 4.6 shortlist (frozen before batch separation is examined)
SHORTLIST = [
    "si_frac_solid", "si_d50_aw_um", "si_d90_aw_um", "si_num_density_mm2",
    "si_solidity_med", "si_quadrat_cv", "pore_frac_deep",
    "pore_chord_h_mean_um", "pore_chord_v_mean_um",
    "aniso_pore_chord_ratio", "aniso_carbon_chord_ratio",
    "s2_len_pore_h_px", "pore_percolating_frac_v",
    "si_contact_pore_frac", "si_contact_carbon_frac",
    "crack_density_um_per_mm2",
]

# one-line battery meanings for the report (Section 4.5 column 4)
MEANINGS = {
    "si_frac_solid": "Si-candidate share of solids: sets capacity, swelling and first-cycle loss",
    "si_frac_total": "Si-candidate share of total volume",
    "si_d50_aw_um": "Si-candidate size D50: drives fracture, SEI growth and swelling; drift = grade change",
    "si_d90_aw_um": "Si-candidate size D90: tail of the size distribution",
    "si_d10_aw_um": "Si-candidate size D10: fine fraction of the size distribution",
    "si_span": "Width of the Si-candidate size distribution",
    "si_num_density_mm2": "Si-candidate particle density: change at constant fraction = size change",
    "si_solidity_med": "Si-candidate solidity: fingerprints the Si grade",
    "si_aspect_med": "Si-candidate aspect ratio: fingerprints the Si grade",
    "si_circularity_med": "Si-candidate circularity: fingerprints the Si grade",
    "si_interior_texture": "Si-candidate internal texture: porous vs solid Si",
    "si_quadrat_cv": "Si spatial uniformity: agglomeration at constant loading = mixing problem",
    "si_clark_evans_R": "Si clustering index: <1 clustered, ~1 random",
    "si_agglomerate_frac": "Share of Si in large agglomerates: swell ~120%, lose contact",
    "pore_frac_deep": "Deep-pore fraction: lower bound on porosity; governs ionic transport and wetting",
    "pore_frac_slope_per_level": "Sensitivity of pore fraction to threshold: stability of the pore call",
    "ambiguous_frac": "BSE-dark/ETD-bright pixels: shallow pores or artefacts, counted not used",
    "pore_chord_h_mean_um": "Horizontal pore size: calendering shrinks pores",
    "pore_chord_v_mean_um": "Vertical pore size: through-plane wetting and fast-charge paths",
    "pore_chord_h_p90_um": "Large horizontal pores: wetting and fast-charge paths",
    "pore_lt_d50_um": "Pore local thickness D50: characteristic pore width",
    "aniso_pore_chord_ratio": "Pore alignment parallel to collector: raises through-plane tortuosity, slows fast-charge; consistent with calendering",
    "aniso_carbon_chord_ratio": "Flake alignment parallel to collector: through-plane tortuosity and fast-charge limit",
    "st_coherence": "Structure-tensor orientation coherence: flake alignment",
    "st_orientation_deg": "Dominant flake orientation",
    "s2_len_pore_h_px": "Correlation length of the pore network (horizontal)",
    "s2_len_pore_v_px": "Correlation length of the pore network (vertical)",
    "s2_len_si_px": "Correlation length of the Si phase spacing",
    "s2_integral_range_pore_px2": "Integral range of the pore indicator: representative-area scale",
    "si_frac_se_imagerep": "Principled error bar on Si fraction (image-representativity)",
    "pore_percolating_frac_v": "Share of pores spanning top-bottom: connected through-plane transport",
    "pore_percolating_frac_h": "Share of pores spanning left-right",
    "pore_euler_density_mm2": "Pore network topology: connectivity vs isolated pores",
    "interface_pore_solid_um_per_um2": "Pore-solid interface density: exposed surface, SEI/first-cycle loss",
    "si_contact_pore_frac": "Si surface facing pores: buffer space for ~3-4x Si expansion",
    "si_contact_carbon_frac": "Si surface facing carbon: electronic wiring",
    "crack_density_um_per_mm2": "Crack length per area: impedance rise and Si crack cascade",
    "largest_void_ecd_um": "Largest single void: local defect scale",
    "hiz_inclusion_count_mm2": "High-Z inclusions: separator puncture risk",
    "vertical_pore_slope": "Vertical pore gradient: drying/binder-migration hint (diagnostic only)",
    "vertical_si_slope": "Vertical Si gradient: drying hint (diagnostic only)",
}
